const actionTypes = {
  GET_CATEGORIES_START: 'GET_CATEGORIES_START',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILED: 'GET_CATEGORIES_FAILED',

  GET_PRODUCTS_START: 'GET_PRODUCT_START',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCTS_FAILED: 'GET_PRODUCT_FAILED',

  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  CLEAR_ITEM: 'CLEAR_ITEM',
  REDUCE_ITEM: 'REDUCE_ITEM',

  TOGGLE_CART: 'TOGGLE_CART',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default actionTypes;
