const actionTypes = {
  GET_CATEGORIES_START: 'GET_CATEGORIES_START',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILED: 'GET_CATEGORIES_FAILED',
  TOGGLE_CART: 'TOGGLE_CART',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default actionTypes;
